# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a451cad2eb68a1ea0cfd3fa389a59a0fab067d1439c33736d017986176fbc7f0d5af171372cde97907d2306d046dbf060551fbb1a7d2573dfc69ae4540e61776

test:
  secret_key_base: 8745b63afa32fe3e560a7158edbfbdcc8a4c0af7886b7ace00348319817d091cc811c8753a65cf06d63c4e0b895f5fe33269db45a83885ff6631ca66d63bfa3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
